#!/usr/bin/env python3
"""Embed img/brand/bblogo.png as a data URL for Print Shop (no runtime fetch/cache)."""
from __future__ import annotations

import base64
import io
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:  # pragma: no cover
    raise SystemExit('Pillow required: pip install pillow') from exc

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'img' / 'brand' / 'bblogo.png'
OUT = ROOT / 'menuplanner' / 'js' / 'printLogoAsset.js'

im = Image.open(SRC).convert('RGBA')
width = 240
height = max(1, round(im.height * (width / im.width)))
small = im.resize((width, height), Image.Resampling.LANCZOS)
buf = io.BytesIO()
small.save(buf, format='PNG', optimize=True)
payload = base64.b64encode(buf.getvalue()).decode('ascii')
OUT.write_text(
    '/** Embedded medallion logo for Print Shop — generated by scripts/generate-print-logo.py */\n'
    f"export const PRINT_LOGO_DATA_URL = 'data:image/png;base64,{payload}';\n",
    encoding='utf-8',
)
print(f'Wrote {OUT} ({len(buf.getvalue())} bytes PNG)')
